import hr_employee  # noqa
import registros  # noqa
import registros_reportes  # noqa
import registros_reportes_line  # noqa
import reports  # noqa
import res_company  # noqa
import res_partner  # noqa
import res_users  # noqa
import utils  # noqa
import verificacion  # noqa
import wizards  # noqa
